In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [4]:
import IPython
print(IPython.sys_info())

{'commit_hash': 'd0b255042',
 'commit_source': 'installation',
 'default_encoding': 'cp1252',
 'ipython_path': 'C:\\Users\\srpra\\Anaconda3\\envs\\pytorchenv\\lib\\site-packages\\IPython',
 'ipython_version': '7.13.0',
 'os_name': 'nt',
 'platform': 'Windows-10-10.0.18362-SP0',
 'sys_executable': 'C:\\Users\\srpra\\Anaconda3\\envs\\pytorchenv\\python.exe',
 'sys_platform': 'win32',
 'sys_version': '3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit '
                '(AMD64)]'}


In [5]:
array = np.array(mylist)

In [6]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
mymatrix = np.array(mylist)

In [9]:
mymatrix.shape

(3, 3)

In [13]:
np.arange(0,11,2) #Just integers, does not include the last number, asks for the spacing

array([ 0,  2,  4,  6,  8, 10])

In [17]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
np.ones((3,3)) * 4 + 3 # Does the operation on every number in the array unlike  python lists

array([[7., 7., 7.],
       [7., 7., 7.],
       [7., 7., 7.]])

In [23]:
np.linspace(0,10,20) # Real numbers, includes the last number, asks for the number of numbers

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.random.rand(5,5)   # Uniform distribution between 0 and 1

array([[0.36573112, 0.84421459, 0.52628428, 0.82959378, 0.7781899 ],
       [0.54318571, 0.35508647, 0.24495925, 0.08936779, 0.42155342],
       [0.92638476, 0.24005557, 0.05154618, 0.02905752, 0.36726548],
       [0.27519411, 0.18535686, 0.19482019, 0.75614516, 0.75285257],
       [0.83749891, 0.87706337, 0.20627522, 0.53921642, 0.94806485]])

In [28]:
np.random.randn(5,5)  # Standard normal distribution (Mean-0, Std-1)

array([[-0.37383652, -1.03300916, -0.60544992, -1.9717571 , -0.54179991],
       [-0.66433021, -1.06782576, -0.1254955 ,  0.7288031 ,  0.49105092],
       [-0.23421433, -2.21763485, -0.31261212, -0.56693828, -0.32252925],
       [-0.82981595, -0.16103818,  0.19219923, -0.70997915, -1.90708928],
       [-0.55911282, -1.13420935, -0.93111081, -0.39265917, -0.06775311]])

In [31]:
np.random.normal(loc = 0, scale = 3)  # Mention mean and std

0.7876875028801049

In [32]:
np.random.randint(1,35,10)

array([25,  6, 34, 24, 24, 10, 27,  9, 19,  9])

In [33]:
np.random.seed(42)  # Must be in the same cell (Seed and the random numbers)
np.random.rand(4)   # To generate the same set of random numbers by setting the seed

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [34]:
arr = np.arange(25)

In [35]:
ranarr = np.random.randint(0,50,10)

In [36]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [38]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
ranarr.max()

39

In [40]:
ranarr.min()

2

In [41]:
ranarr.argmax()

7

In [42]:
ranarr.argmin()

9

In [43]:
ranarr.dtype

dtype('int32')

In [44]:
arr = np.arange(0,11)

In [45]:
arr[8]

8

In [46]:
arr[1:5]

array([1, 2, 3, 4])

In [47]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [48]:
arr[:5]

array([0, 1, 2, 3, 4])

In [49]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [51]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [52]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
slice_of_arr = arr[0:6]   # Still part of the original array

In [56]:
slice_of_arr[:] = 99   # Changes the original array too!

In [57]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [58]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [59]:
arr_copy = arr.copy()  # Copy's without the location

In [60]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [62]:
arr_2d.shape

(3, 3)

In [64]:
arr_2d[1][2]

30

In [65]:
arr_2d[2,2]

45

In [68]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [69]:
arr = np.arange(1,11)

In [70]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [71]:
bool_arr = arr > 4

In [72]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [73]:
arr[arr < 5]

array([1, 2, 3, 4])

In [74]:
arr[arr <= 8]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [75]:
arr = np.arange(0,10)

In [76]:
arr  + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [77]:
arr / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

In [78]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [79]:
(arr + 2)/100

array([0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11])

In [80]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [82]:
1/arr

C:\Users\srpra\Anaconda3\envs\pytorchenv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [83]:
arr/arr

C:\Users\srpra\Anaconda3\envs\pytorchenv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [84]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [85]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [86]:
arr.sum()

45

In [87]:
arr.max()


9

In [88]:
arr.mean()

4.5

In [90]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [92]:
arr_2d.sum()

78

In [93]:
arr_2d.sum(axis = 0)

array([15, 18, 21, 24])

In [94]:
arr_2d.sum(axis = 1)

array([10, 26, 42])

In [95]:
arr_2d.mean(axis = 1)

array([ 2.5,  6.5, 10.5])