In [1]:
import torch 

In [2]:
import numpy as np

In [3]:
torch.__version__

'1.1.0'

In [4]:
arr = np.array([1,2,3,4,5])

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arr.dtype

dtype('int32')

In [7]:
type(arr)

numpy.ndarray

In [9]:
x = torch.from_numpy(arr)

In [10]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [11]:
type(x)

torch.Tensor

In [12]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [13]:
x.dtype

torch.int32

In [15]:
arr2d = np.arange(0.0,12.0)
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [17]:
arr2d = arr2d.reshape(4,3)

In [18]:
x2 = torch.as_tensor(arr2d)

In [19]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [20]:
arr[0] = 99

In [21]:
arr

array([99,  2,  3,  4,  5])

In [22]:
x

tensor([99,  2,  3,  4,  5], dtype=torch.int32)

In [23]:
my_arr = np.arange(0,10) 

In [24]:
my_tensor = torch.tensor(my_arr)

In [25]:
my_other_tensor = torch.as_tensor(my_arr)

In [26]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [27]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [28]:
new_arr = np.array([1,2,3])

In [29]:
torch.tensor(new_arr)

tensor([1, 2, 3], dtype=torch.int32)

In [34]:
xtensor = torch.Tensor(new_arr)

In [35]:
xtensor.dtype

torch.float32

In [38]:
torch.empty(2,2)

tensor([[2.0000e+00, 2.7729e-02],
        [1.7747e-10, 4.5912e-41]])

In [41]:
torch.zeros(3,3,dtype=torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [44]:
torch.rand(3,3)

tensor([[0.3570, 0.7743, 0.7818],
        [0.3459, 0.6376, 0.6658],
        [0.8229, 0.9560, 0.4053]])

In [45]:
torch.arange(0,11)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
torch.linspace(0,10,20).reshape(4,5)

tensor([[ 0.0000,  0.5263,  1.0526,  1.5789,  2.1053],
        [ 2.6316,  3.1579,  3.6842,  4.2105,  4.7368],
        [ 5.2632,  5.7895,  6.3158,  6.8421,  7.3684],
        [ 7.8947,  8.4211,  8.9474,  9.4737, 10.0000]])

In [55]:
torch.randn(3,3)

tensor([[ 0.5381,  0.8224,  1.0595],
        [-1.3681,  0.1480,  0.0042],
        [ 0.2473,  1.6389, -1.0104]])

In [59]:
torch.randint(0,31,(5,5))

tensor([[ 0, 12,  3, 10, 16],
        [18, 25,  0, 15, 17],
        [21, 26, 29, 12, 10],
        [ 8, 19,  6, 27,  9],
        [ 8, 24, 27, 18, 22]])

In [60]:
x = torch.zeros(2,5)

In [61]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [69]:
torch.rand_like(x)

tensor([[0.9612, 0.0119, 0.6743, 0.8911, 0.4736],
        [0.1974, 0.9539, 0.9553, 0.0554, 0.0018]])

In [70]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [72]:
x = torch.arange(6).reshape(3,2)

In [73]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [75]:
x[1,1]

tensor(3)

In [79]:
x[:,1].shape

torch.Size([3])

In [78]:
x[:,1:].shape

torch.Size([3, 1])

In [80]:
x = torch.arange(10)

In [81]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [83]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [86]:
x = x.reshape(2,5)

In [87]:
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [88]:
x = torch.arange(10)

In [89]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
x.shape

torch.Size([10])

In [93]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [94]:
z = x.view(2,5)

In [95]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [96]:
x[0] = 9999

In [97]:
z

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [98]:
x

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [99]:
x = torch.arange(10)

In [100]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
x.shape

torch.Size([10])

In [103]:
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [104]:
x.reshape(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [105]:
a = torch.tensor([1.,2.,3.])

In [106]:
b = torch.tensor([4.,5.,6.])

In [107]:
a

tensor([1., 2., 3.])

In [108]:
a.dtype

torch.float32

In [109]:
b

tensor([4., 5., 6.])

In [110]:
a + b

tensor([5., 7., 9.])

In [111]:
torch.add(a,b)

tensor([5., 7., 9.])

In [112]:
a.mul(b)

tensor([ 4., 10., 18.])

In [113]:
a

tensor([1., 2., 3.])

In [114]:
a.mul_(b)

tensor([ 4., 10., 18.])

In [115]:
a

tensor([ 4., 10., 18.])

In [116]:
torch.sin(a)

tensor([-0.7568, -0.5440, -0.7510])

In [117]:
a = torch.tensor([1.,2.,3.])

In [118]:
a

tensor([1., 2., 3.])

In [119]:
b

tensor([4., 5., 6.])

In [120]:
a*b

tensor([ 4., 10., 18.])

In [121]:
a.dot(b)

tensor(32.)

In [122]:
a = torch.tensor([[0,2,4],[1,3,5]])

In [123]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [124]:
b = torch.tensor([[6,7],[8,9],[10,11]])

In [125]:
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [126]:
a.matmul(b)

tensor([[56, 62],
        [80, 89]])

In [127]:
torch.mm(a,b)

tensor([[56, 62],
        [80, 89]])

In [128]:
a @ b

tensor([[56, 62],
        [80, 89]])

In [ ]:
x = torch.tensor([2])