In [1]:
import torch

In [2]:
x = torch.tensor(2.0, requires_grad=True)

In [3]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1

In [4]:
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [5]:
y.backward()

In [6]:
x.grad 

tensor(93.)

In [7]:
x = torch.tensor([[1.,2.,3.],[3.,2.,1.]],requires_grad=True)

In [8]:
x

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)

In [9]:
y = 3*x + 2

In [10]:
print(y)

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)


In [11]:
z = 2*y**2

In [13]:
print(z)

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)


In [14]:
out = z.mean()

In [15]:
print(out)

tensor(140., grad_fn=<MeanBackward0>)


In [16]:
out.backward()

In [17]:
print(x.grad)

tensor([[10., 16., 22.],
        [22., 16., 10.]])


In [18]:
a = torch.tensor([[1.,2.,3.],[5.,3.,7.],[2.,6.,5.]],requires_grad =True)

In [19]:
a

tensor([[1., 2., 3.],
        [5., 3., 7.],
        [2., 6., 5.]], requires_grad=True)

In [20]:
b = torch.sin(a)

In [21]:
b

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.9589,  0.1411,  0.6570],
        [ 0.9093, -0.2794, -0.9589]], grad_fn=<SinBackward>)

In [23]:
print(a.grad)  # No gradient since b.backward() is not mentioned 

None


In [25]:
c = b.mean()  # Calculating mean (or any aggregate) since gradient cannot be evaluated 

In [26]:
c.backward()

In [28]:
a.grad

tensor([[ 0.0600, -0.0462, -0.1100],
        [ 0.0315, -0.1100,  0.0838],
        [-0.0462,  0.1067,  0.0315]])